# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5e5ded46787140a638132f2bc0a44ea6eda9245180c50c2838d799428e15f722082d98add5ab71659b0fd43bc3888eb00960fa3d792ee5a4c297fafa0aec0b8

test:
  secret_key_base: 497b9bcea3c5aa51eddd932a92c2c0ca8113507ec8ea660d58e32efca084ff6fe8b416ec41b3cf144f290c78f417f3ada8841f23b82ea72410f0eb1cbd350ec8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
